name = "newsnow"
pages_build_output_dir = "dist/output/public"
compatibility_date = "2024-10-03"

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "hotnew"
database_id = "7d5d9c5e-6f68-470a-bb84-168bf8cfc8c5"
